#pragma once

#include "../harmony/StyleProfile.h"
#include <array>
#include <cstdint>

namespace morph
{

/** A validated GOLD seed: style + seed + its generated degree sequence. */
struct BankEntry
{
    StyleId style;
    uint32_t seed;
    std::array<uint8_t, 4> degrees;
    float score;
};

/** The compiled GOLD bank (generated by tools/MorphBankTool; see
    src/engine/bank/GoldBank.inc). Validation: tests/bank/BankTests.cpp
    re-checks every entry against QualityMetrics thresholds. */
extern const BankEntry goldBank[];
extern const int goldBankCount;

/** Bank lookup for a style (nullptr when empty). */
const BankEntry* bankEntriesForStyle (StyleId style, int& count);

} // namespace morph
