/**
 * MorphBankTool — progression bank generation, validation, deduplication,
 * audition (§100).
 *
 *   MorphBankTool --generate [--count N-per-style] [--out <path-to-GoldBank.inc>]
 *   MorphBankTool --audition <index>
 *   MorphBankTool --stats
 *
 * Generation: for each style, seeds are generated, quality-validated
 * (QualityMetrics::passesGold on the realized plan), deduplicated by degree
 * sequence, and the strongest are written grouped by style.
 */
#include "../src/engine/progression/ProgressionGenerator.h"
#include "../src/engine/bank/ProgressionBank.h"
#include <juce_core/juce_core.h>
#include <algorithm>
#include <set>

using namespace morph;

namespace
{
    uint32_t hashDegrees (const std::array<int, 4>& d)
    {
        return (uint32_t) (d[0] * 1000 + d[1] * 100 + d[2] * 10 + d[3]);
    }

    const char* styleEnumName (StyleId id)
    {
        switch (id)
        {
            case StyleId::modernRnB: return "modernRnB";
            case StyleId::darkRnB:   return "darkRnB";
            case StyleId::neoSoul:   return "neoSoul";
            case StyleId::emotional: return "emotional";
            case StyleId::darkPop:   return "darkPop";
            case StyleId::trap:      return "trap";
            default:                 return "modernRnB";
        }
    }
}

int main (int argc, char* argv[])
{
    const juce::ArgumentList args (argc, argv);

    const auto key = KeyContext::cMinor();
    ProgressionGenerator gen;

    if (args.containsOption ("--audition"))
    {
        const int index = args.getValueForOption ("--audition").getIntValue();
        if (index < 0 || index >= goldBankCount)
        {
            std::cerr << "audition index out of range (0.." << goldBankCount - 1 << ")\n";
            return 1;
        }

        const auto& entry = goldBank[index];
        std::cout << "GOLD #" << index << "  style=" << styleEnumName (entry.style)
                  << "  seed=" << entry.seed << "  degrees="
                  << (int) entry.degrees[0] << "-" << (int) entry.degrees[1] << "-"
                  << (int) entry.degrees[2] << "-" << (int) entry.degrees[3]
                  << "  score=" << entry.score << "\n";

        Realizer realizer;
        realizer.key = key;
        realizer.style = StyleProfile::get (entry.style);
        VoiceLeadingMemory mem;
        for (int slot = 0; slot < 4; ++slot)
        {
            const auto r = realizer.realize (ScaleDegree { entry.degrees[(size_t) slot] }, mem, slot);
            juce::String line = "  " + chordSymbolToString (r.candidate.chord, true).paddedRight (' ', 9);
            for (int v = 0; v < r.voicing.count; ++v)
                line += juce::String (r.voicing.voices[(size_t) v].pitch.value) + " ";
            std::cout << line.toStdString() << "\n";
        }
        return 0;
    }

    if (args.containsOption ("--generate"))
    {
        int perStyle = 50; // 50 × 6 styles = 300 GOLD (§100)
        if (args.containsOption ("--count"))
        {
            const auto v = args.getValueForOption ("--count").getIntValue();
            if (v > 0)
                perStyle = v;
        }

        juce::File out = juce::File::getCurrentWorkingDirectory()
                             .getChildFile ("src/engine/bank/GoldBank.inc");
        if (args.containsOption ("--out"))
            out = juce::File (args.getValueForOption ("--out"));

        juce::String content;
        content << "// GOLD progression bank — generated by MorphBankTool.\n"
                   "// Validated: passesGold on realized plans; deduplicated per style.\n";

        int totalKept = 0;

        for (int styleInt = 0; styleInt < numImplementedStyles; ++styleInt)
        {
            const auto style = StyleProfile::get ((StyleId) styleInt);

            struct Cand { uint32_t seed; std::array<int, 4> degrees; float score; };
            std::vector<Cand> kept;
            std::set<uint32_t> seen;

            int rejected = 0;
            for (uint32_t seed = 1; (int) kept.size() < perStyle && seed < 400000; ++seed)
            {
                auto g = gen.generate (style, key, seed * 2654435761u + 17u);

                if (! QualityMetrics::passesGold (g.metrics))
                {
                    ++rejected;
                    continue;
                }
                if (! seen.insert (hashDegrees (g.degrees)).second)
                    continue; // duplicate degree sequence

                kept.push_back ({ seed, g.degrees, g.score });
            }

            // Strongest first.
            std::sort (kept.begin(), kept.end(),
                       [] (const Cand& a, const Cand& b) { return a.score > b.score; });
            if ((int) kept.size() > perStyle)
                kept.resize ((size_t) perStyle);

            content << "\n    // " << style.displayName << " (" << (int) kept.size() << ")\n";
            for (const auto& c : kept)
            {
                content << "    { StyleId::" << styleEnumName (style.id) << ", " << juce::String (c.seed) << "u, { "
                        << (int) c.degrees[0] << ", " << (int) c.degrees[1] << ", "
                        << (int) c.degrees[2] << ", " << (int) c.degrees[3] << " }, "
                        << juce::String (c.score, 3) << "f },\n";
            }

            std::cout << style.displayName << ": kept " << kept.size()
                      << " (rejected " << rejected << ")\n";
            totalKept += (int) kept.size();
        }

        out.replaceWithText (content);
        std::cout << "wrote " << out.getFullPathName() << " — " << totalKept << " GOLD entries\n";
        return 0;
    }

    if (args.containsOption ("--stats"))
    {
        std::cout << "GOLD bank entries: " << goldBankCount << "\n";
        for (int s = 0; s < numImplementedStyles; ++s)
        {
            int count = 0;
            bankEntriesForStyle ((StyleId) s, count);
            std::cout << "  " << StyleProfile::get ((StyleId) s).displayName << ": " << count << "\n";
        }
        return 0;
    }

    std::cout << "MorphBankTool: --generate [--count N] [--out path] | --audition N | --stats\n";
    return 0;
}
